### ISSUE TITLE
action does not update issue correctly

### ISSUE THREAD

**Issue by fluxsaas** [Bhacaz/bundler-outdated-action#2]
Hey!

if i followed your instructions from the readme but the issue is update with a blank table:

![Bildschirmfoto 2020-09-01 um 14 34 22](https://user-images.githubusercontent.com/13223/91851898-419c4f80-ec60-11ea-9f8f-fa64283071f4.png)

etract from Gemfile.lock:

```
....
RUBY VERSION
   ruby 2.6.3p62

BUNDLED WITH
   2.1.4
```

rubnning `bundle _2.1.4_ outdated  --only-explicit --strict` locally works fine and returns

```
.....
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies................

Outdated gems included in the bundle:
  * wkhtmltopdf-heroku (newest 2.12.5.0, installed 2.12.4.0) in group "default"
....
```

**Comment by Bhacaz** [comment]
Hey, thanks for the issue.

I don't thing the problem is in the code, since the `Parsing` class seems to work with the output you provided.

```ruby 
>> require_relative 'parsing'
true
>> outputs = <<-S
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies................
Outdated gems included in the bundle:
  * wkhtmltopdf-heroku (newest 2.12.5.0, installed 2.12.4.0) in group "default"
S
"Fetching gem metadata from https://rubygems.org/.........\nFetching gem metadata from https://rubygems.org/.\nResolving dependencies................\nOutdated gems included in the bundle:\n  * wkhtmltopdf-heroku (newest 2.12.5.0, installed 2.12.4.0) in group \"default\"\n"
>> parsing = Parsing.new(outputs)
#<Parsing:0x00007ff1f9091738 @output="Fetching gem metadata from https://rubygems.org/.........\nFetching gem metadata from https://rubygems.org/.\nResolving dependencies................\nOutdated gems included in the bundle:\n  * wkhtmltopdf-heroku (newest 2.12.5.0, installed 2.12.4.0) in group \"default\"\n", @data=[{:name=>"wkhtmltopdf-heroku", :newest=>"2.12.5.0", :installed=>"2.12.4.0", :groups=>"default"}]>
>> puts parsing.to_md
![](https://github.com//workflows//badge.svg)

`bundle outdated  --only-explicit --strict`

|Gem|Installed|Newest|Groups|
|---|---|---|---|
|[wkhtmltopdf-heroku](https://rubygems.org/gems/wkhtmltopdf-heroku)|2.12.4.0|2.12.5.0|default|
```

---

Can you share your workflow file? There is probably a difference with your local and the Github Action environment.

**Comment by fluxsaas** [comment]
pretty much the same as in the readme:

```
name: 'Outdated Gems'

on: push

jobs:
  outdated_gems:
    runs-on: ubuntu-latest
    name: Outdated gems
    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.0'
      - name: 'Pull outdated gem action script'
        uses: actions/checkout@v2
        with:
          repository: 'Bhacaz/bundler-outdated-action'
      - name: 'Check outdated gems'
        run: 'ruby main.rb'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMFILE_REPOSITORY: ${{ github.repository }}
```
